tabWidth: 4
printWidth: 80
useTabs: true
semi: true
singleQuote: true
quoteProps: as-needed
trailingComma: none
bracketSpacing: false
arrowParens: avoid
bracketSameLine: false
jsxSingleQuote: false
overrides:
  - files:
      - '*.yaml'
      - '*.yml'
    options:
      tabWidth: 2
      useTabs: false
